(function () {
  "use strict";
  var STATES = ["default","vent_detail","vent_history","vent_alarms"];
  var labels = {default:"Tổng quan",vent_detail:"Giám sát",vent_history:"Lịch sử",vent_alarms:"Cảnh báo"};
  var app = document.getElementById("app"), vm;
  function esc(v){return String(v == null ? "" : v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c];});}
  function route(){var id=location.hash.replace(/^#/,"")||"default";return STATES.indexOf(id)>=0?id:"default";}
  function metric(key){return vm.metrics[key]||{value:null,unit:"",quality:"UNKNOWN"};}
  function value(m){return m.value===null||m.value===undefined?"--":esc(m.value)+(m.unit?" <small>"+esc(m.unit)+"</small>":"");}
  function plainValue(m){return m.value===null||m.value===undefined?"--":esc(m.value)+(m.unit?" "+esc(m.unit):"");}
  function header(state){return '<header class="vent-header"><div class="vent-header__top"><strong class="vent-header__title">SIBA · Thông gió</strong><span class="vent-header__scope">'+esc(vm.scope.farm)+' · '+esc(vm.scope.area)+'</span><b class="demo-badge">'+esc(vm.badgeLabel)+'</b></div><nav class="state-tabs" aria-label="Trạng thái dashboard">'+STATES.map(function(s){return '<a href="#'+s+'" class="'+(s===state?'active':'')+'">'+labels[s]+'</a>';}).join("")+'</nav></header>';}
  function kpi(label,key,icon){var m=metric(key);return '<article class="kpi"><div class="kpi__head"><span class="kpi__icon">'+icon+'</span>'+label+'</div><b class="kpi__value">'+value(m)+'</b><span class="kpi__quality quality-'+m.quality+'">'+m.quality+(m.ts?' · '+new Date(m.ts).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):'')+'</span></article>';}
  function summaryKpi(label,count,icon){return '<article class="kpi"><div class="kpi__head"><span class="kpi__icon">'+icon+'</span>'+label+'</div><b class="kpi__value">'+esc(count)+'</b><span class="kpi__quality">DEMO SUMMARY</span></article>';}
  function overview(){return '<section class="view"><div class="kpi-grid">'+summaryKpi('Tổng số nhà',vm.summary.barns||0,'⌂')+summaryKpi('Đang trực tuyến',vm.summary.online||0,'●')+summaryKpi('Cần chú ý',vm.summary.attention||0,'!')+summaryKpi('Cảnh báo đang mở',vm.summary.activeAlarms||0,'△')+'</div><div class="overview-grid"><section class="panel"><div class="panel__head"><div><h2>Toàn trại</h2><p>Chọn một nhà để xem giám sát thông gió.</p></div><span class="muted">Nguồn fixture cô lập</span></div><div class="barn-grid">'+vm.barns.map(function(b){return '<button class="barn-card" data-open-detail><b>'+esc(b.label)+'</b><span class="status-'+b.connectivity+'">'+b.connectivity+'</span><span class="quality-'+b.freshness+'">Dữ liệu: '+b.freshness+'</span><span>Chế độ: '+esc(b.mode)+'</span><span class="status-'+b.alarm+'">Cảnh báo: '+b.alarm+'</span></button>';}).join('')+'</div></section><section class="panel"><div class="panel__head"><div><h2>Cảnh báo ưu tiên</h2><p>Chỉ xem; không có thao tác vòng đời.</p></div><a href="#vent_alarms" class="muted">Xem tất cả →</a></div><div class="alarm-list">'+vm.alarms.map(function(a){return '<article class="alarm-mini '+a.severity+'"><b>'+esc(a.type)+'</b><span>'+esc(a.message)+'</span><small>'+esc(a.originator)+'</small></article>';}).join('')+'</div></section></div>'+footer()+'</section>';}
  function equipmentCards(){return vm.equipment.map(function(e){return '<article class="equipment-card"><small>'+esc(e.label)+'</small><b class="status-'+esc(e.state)+'">'+esc(e.state)+'</b><span class="muted">'+esc(e.quality)+'</span></article>';}).join('');}
  function synoptic(){var fans=vm.equipment.slice(0,6);return '<div class="synoptic" role="region" aria-label="Sơ đồ thông gió có thể cuộn ngang"><svg viewBox="0 0 900 390" role="img" aria-label="Sơ đồ thông gió chỉ đọc"><rect class="zone" x="45" y="70" width="810" height="235" rx="6"/><path class="pipe" d="M90 188H810"/><text class="svg-label" x="450" y="48">NHÀ '+esc(vm.scope.selectedBarn)+'</text>'+fans.map(function(f,i){var x=130+i*128;return '<g class="fan '+esc(f.state)+'"><circle cx="'+x+'" cy="188" r="31"/><path class="pipe" d="M'+(x-14)+' '+(188-14)+'L'+(x+14)+' '+(188+14)+'M'+(x+14)+' '+(188-14)+'L'+(x-14)+' '+(188+14)+'"/><text class="svg-label" x="'+x+'" y="245">'+esc(f.label)+'</text><text class="svg-sub" x="'+x+'" y="264">'+esc(f.state)+'</text></g>';}).join('')+'<g class="louver"><rect x="312" y="84" width="276" height="24" rx="4"/><text class="svg-sub" x="450" y="101">Cửa chớp trần · '+plainValue(vm.louvers[0])+'</text><rect x="312" y="280" width="276" height="24" rx="4"/><text class="svg-sub" x="450" y="297">Cửa chớp hông · '+plainValue(vm.louvers[1])+'</text></g></svg></div>';}
  function detail(){var mode=metric('operation_mode'),control=metric('fan_control_mode'),stage=metric('ventilation_stage'),online=metric('controller_online');return '<section class="view"><div class="kpi-grid">'+kpi('Nhiệt độ trong nhà','temperature_indoor','°')+kpi('Nhiệt độ ngoài trời','temperature_outdoor','°')+kpi('Nhiệt độ cảm nhận','temperature_feel','≈')+kpi('Độ ẩm trong nhà','humidity','%')+'</div><div class="detail-layout"><section class="panel"><div class="panel__head"><div><h2>Giám sát nhà '+esc(vm.scope.selectedBarn)+'</h2><p>Sơ đồ read-only · trạng thái fixture có chủ đích</p></div><span class="quality-'+vm.louvers[0].quality+'">'+vm.louvers[0].quality+'</span></div>'+synoptic()+'<div class="equipment-grid">'+equipmentCards()+'</div></section><aside class="panel"><div class="panel__head"><div><h2>Bộ điều khiển</h2><p>Không có lệnh điều khiển</p></div></div><div class="controller-summary"><div class="summary-row"><span>Kết nối</span><b>'+ (online.value===true?'ONLINE':'UNKNOWN')+'</b></div><div class="summary-row"><span>Chế độ</span><b>'+value(mode)+'</b></div><div class="summary-row"><span>Điều khiển quạt</span><b>'+value(control)+'</b></div><div class="summary-row"><span>Cấp hiện tại</span><b>'+value(stage)+' / --</b></div><div class="notice">Số cấp hợp lệ chưa được runtime xác nhận; demo không suy ra 6/9 từ tài liệu.</div><a href="#vent_history" class="state-tabs">Xem lịch sử →</a></div></aside></div>'+footer()+'</section>';}
  function seriesPath(key){var vals=vm.history.map(function(x){return x[key];}),valid=vals.filter(function(v){return typeof v==='number';}),min=Math.min.apply(null,valid),max=Math.max.apply(null,valid),penDown=false;return vals.map(function(v,i){if(typeof v!=='number'){penDown=false;return '';}var x=55+i*(620/(vals.length-1)),y=245-((v-min)/(max-min||1))*175,command=penDown?'L':'M';penDown=true;return command+x.toFixed(1)+' '+y.toFixed(1);}).join(' ');}
  function history(){return '<section class="view"><section class="panel"><div class="panel__head"><div><h2>Lịch sử môi trường · 6 giờ</h2><p>Khoảng thời gian demo cục bộ; điểm thiếu giữ thành khoảng trống logic, không đổi thành 0.</p></div></div><div class="legend"><span><i style="background:#00d4e0"></i>Trong nhà</span><span><i style="background:#ffc857"></i>Ngoài trời</span><span><i style="background:#6aa9ff"></i>Độ ẩm</span></div><div class="chart-wrap"><svg class="chart" viewBox="0 0 720 280"><path class="grid" d="M55 70H675M55 128H675M55 187H675M55 245H675"/><path class="inside" d="'+seriesPath('temperature_indoor')+'"/><path class="outside" d="'+seriesPath('temperature_outdoor')+'"/><path class="humidity" d="'+seriesPath('humidity')+'"/><text x="55" y="266">02:30</text><text x="625" y="266">08:30</text></svg></div></section><section class="panel table-wrap"><table class="data-table"><thead><tr><th>Thời gian</th><th>Nhiệt độ trong</th><th>Nhiệt độ ngoài</th><th>Độ ẩm</th><th>Chất lượng</th></tr></thead><tbody>'+vm.history.slice().reverse().map(function(r){return '<tr><td>'+new Date(r.ts).toLocaleString('vi-VN')+'</td><td>'+(r.temperature_indoor==null?'--':r.temperature_indoor+' °C')+'</td><td>'+r.temperature_outdoor+' °C</td><td>'+r.humidity+' %RH</td><td>'+(r.temperature_indoor==null?'<span class="pill quality-UNKNOWN">MISSING</span>':'<span class="pill quality-CURRENT">SAMPLE</span>')+'</td></tr>';}).join('')+'</tbody></table></section>'+footer()+'</section>';}
  function alarms(){return '<section class="view"><section class="panel"><div class="panel__head"><div><h2>Cảnh báo & lịch sử</h2><p>Read-only; không acknowledge, clear, shelve hoặc assign.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Mức</th><th>Loại / nội dung</th><th>Nguồn</th><th>Thời gian</th><th>Trạng thái</th></tr></thead><tbody>'+vm.alarms.map(function(a){return '<tr><td><span class="pill status-'+a.severity+'">'+esc(a.severity)+'</span></td><td><b>'+esc(a.type)+'</b><br><span class="muted">'+esc(a.message)+'</span></td><td>'+esc(a.originator)+'</td><td>'+new Date(a.created).toLocaleString('vi-VN')+'</td><td>'+esc(a.status)+'</td></tr>';}).join('')+'</tbody></table></div></section><section class="panel"><div class="panel__head"><div><h2>Giới hạn demo</h2><p>Alarm scope, retention và export production vẫn chưa được xác minh trong VENT-002.</p></div></div><div class="notice">Các alarm ở đây là fixture minh họa; không đại diện trạng thái tenant và không gọi API mutation.</div></section>'+footer()+'</section>';}
  function footer(){return '<footer class="footer"><span>Giám sát chỉ đọc · Fixture '+esc(vm.fixtureVersion)+'</span><span>Sinh lúc '+new Date(vm.generatedAt).toLocaleString('vi-VN')+'</span></footer>';}
  function render(){var state=route();app.innerHTML=header(state)+(state==='default'?overview():state==='vent_detail'?detail():state==='vent_history'?history():alarms());app.querySelectorAll('[data-open-detail]').forEach(function(b){b.addEventListener('click',function(){location.hash='vent_detail';});});}
  window.addEventListener('hashchange',render);
  new window.VentilationAdapter.FixtureSource('../fixtures/ventilation/demo.json').load().then(function(data){vm=data;render();}).catch(function(e){app.innerHTML='<p class="error">Không nạp được fixture demo: '+esc(e.message)+'</p>';});
}());
